-- PILOT SOURCE (Snowflake) — RETAIL.SOURCE.FACT_ORDERS
-- ORDER_TS is TIMESTAMP_LTZ (session-tz relative): must be normalized to UTC on load.

CREATE SCHEMA IF NOT EXISTS RETAIL.SOURCE;

CREATE OR REPLACE TABLE RETAIL.SOURCE.FACT_ORDERS (
  ORDER_ID    NUMBER(38,0) NOT NULL,
  CUSTOMER_ID NUMBER(38,0),
  STORE_ID    NUMBER(38,0),
  ORDER_TS    TIMESTAMP_LTZ(9),
  STATUS      VARCHAR(20),
  ORDER_TOTAL NUMBER(18,4),
  CONSTRAINT PK_FACT_ORDERS PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDERS_CUST  FOREIGN KEY (CUSTOMER_ID) REFERENCES RETAIL.SOURCE.DIM_CUSTOMER(CUSTOMER_ID),
  CONSTRAINT FK_ORDERS_STORE FOREIGN KEY (STORE_ID)    REFERENCES RETAIL.SOURCE.DIM_STORE(STORE_ID)
)
CLUSTER BY (TO_DATE(ORDER_TS))
COMMENT = 'Orders fact. ORDER_TS = TIMESTAMP_LTZ; normalize to UTC on migration.';

INSERT INTO RETAIL.SOURCE.FACT_ORDERS (ORDER_ID, CUSTOMER_ID, STORE_ID, ORDER_TS, STATUS, ORDER_TOTAL)
SELECT
  SEQ4() + 1                                                                        AS ORDER_ID,
  MOD(SEQ4(), 100) + 1                                                              AS CUSTOMER_ID,
  MOD(SEQ4(), 5) + 1                                                                AS STORE_ID,
  DATEADD('hour', -MOD(SEQ4(), 720), CURRENT_TIMESTAMP())                           AS ORDER_TS,
  DECODE(MOD(SEQ4(), 4), 0,'COMPLETED',1,'SHIPPED',2,'PENDING','RETURNED')          AS STATUS,
  CAST(ROUND(20 + MOD(SEQ4(), 500) * 1.7777, 4) AS NUMBER(18,4))                    AS ORDER_TOTAL
FROM TABLE(GENERATOR(ROWCOUNT => 500));
